# Generated by Django 3.2.7 on 2021-10-29 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_login', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teams',
            name='LOB',
        ),
        migrations.AddField(
            model_name='teams',
            name='LOB',
            field=models.ManyToManyField(related_name='lob_for_teams', to='auth_login.LOB'),
        ),
    ]
